---
- name: Revisi칩n de configuraci칩n de los routers Cisco
  hosts: cisco
  tasks:

    - name: Poner nombre y dominio por defecto
      become: true
      ios_system:
        hostname: RouterAWX
        domain_name: pi.local
        domain_search:
          - ansible.com
          - cisco.com

    - name: A침adir banner personalizado
      become: true
      ios_banner:
        banner: login
        text: |
           YOU ARE ACCESING A RESTRICTED SYSTEM!
           IF YOU ARE NOT A NETWORK ENGINEER AND  
           YOU DO NOT BELONG TO THIS ORGANIZATION 
           LEAVE NOW OR LEGAL ACTIONS WILL BE     
           TAKEN AGAINST YOU.                     
           FOR ANY ISSUES, PLEASE CONTACT AN ADMIN
           IMMEDIATELY.

    - name: Crear usuario "ansible"
      become: true
      ios_user:
        name: ansible
        configured_password: ansible
        password_type: password
        state: present
    
    - name: Crear VLAN
      become: true
      ios_vlans:
        config:
        - name: printers
          state: active
          vlan_id: 155
          shutdown: disabled

    - name: Lista la configuraci칩n actual
      become: true
      ios_command:
        commands: show running config

    - name: Guarda los cambios cuando haya modificaciones
      become: true
      ios_config:
        save_when: modified