version: "3.8"
services:
  netbox:
    build: .
    container_name: netbox
    ports:
      - 8000:8000
    networks:
      psql_network:
        ipv4_address: 10.0.2.10
  psql:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      psql_network:
        ipv4_address: 10.0.2.20
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: javsanpae@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      psql_network:
        ipv4_address: 10.0.2.30

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  psql_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
          gateway: 10.0.2.1