# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  vb.memory = "8192"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    
  SHELL
end
