version: '3.4'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    volumes:
      - ./jenkins_home/:/var/jenkins_home/
    ports:
      - 8080:8080
      - 50000:50000
  ansible:
    image: javsanpae/ansible
    volumes:
      - ./ansible:/ansible
    tty: true # si no añadimos esta linea, el contenedor se cierra automaticamente al no detectar trabajos