name: Notificaciones Correo
on: 
    push:
    delete:
    create:
jobs:
  send-push:
    name: Mandar e-mail al detectar un nuevo Push en el repositorio
    runs-on: ubuntu-latest
    steps:
      - name: Enviando correo electronico
        uses: dawidd6/action-send-mail@v3.6.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_ADDRESS}}
          password: ${{secrets.EMAIL_PASSWD}}
          subject: "se ha subido un archivo"
          from: github <noreply@github.com>  
          to: javsanpae@gmail.com
          body: |
             Se han detectado nuevos cambios en el repositorio.
             Para comprobarlos, ve a https://github.com/javsanpae/PROYECTO_ASIR.
             
